version: "3.8"

services:

  # Python-app service configuration
  app:
    build: ./python-app
    ports:
      - 9000-9004:8002  # range of ports for multiple instances
    volumes:
      - app-logs:/app/logs
    env_file:
      - .env
    deploy:
      replicas: 3
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  # Database service configuration
  db:
    image: mysql:8.3.0
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql
    env_file:
      - .env
    command: >
      --log-error=/var/log/mysql/error.log
      --general-log=true
      --general-log-file=/var/log/mysql/general.log
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  # Nginx service configuration
  nginx:
    image: nginx:1.25.4
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - app

volumes:
  app-logs:
  db-data:
  db-logs:

networks:
  app-network:
    driver: bridge
